platform :ios, '8.0'
target 'CopyMe' do
	pod 'MBProgressHUD', '~> 1.0.0'
	pod 'IQKeyboardManager', '~> 5.0.2'
	pod 'SDWebImage', '~> 4.1.0'
	pod 'AFNetworking', '~> 3.1.0'
  	pod 'Masonry', '~> 1.1.0'
	pod 'YYModel', '~> 1.0.4'
	pod 'FMDB', '~> 2.7.2'
end